server:
  port: 8080

spring:
  application:
    jwt:
      secret: ${JWT_SECRET}
      access-token-expiry: 900000       # 15 minutes in ms
      refresh-token-expiry: 604800000   # 7 days in ms

#Datasource and JPA configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#logging configuration
logging:
  level:
    com.resumeanalyzer: DEBUG
    org.hibernate.SQL: DEBUG